### ISSUE TITLE
Melhorias PC3 - Especificação Suplementar e Revisão

### ISSUE THREAD

**Issue by brunna-martins** [Requisitos-de-Software/2023.1-Twitch#107]
## Descrição: 
O monitor disse epara dar uma olhada na US02 (parece mais relacionada com segurança) e na S04 (Usabilidade).

## Critérios de aceitação: 
Atualização do documento conforme o que foi pedido e conforme os padrões estabelecidos pela equipe.

## Tarefas:
Checklist de tarefas a serem feitas.
- [ ] Revisão das partes solicitadas

**Comment by RafaelN0bre** [comment]
Ele estava correto, alteracoes corrigidas no [commit](https://github.com/Requisitos-de-Software/2023.1-Twitch/commit/2cd2c56e5cf8f95b13909c535c3aaaafa5b21182)
