### ISSUE TITLE
Melhorias PC3 - Especificação Suplementar e Funcionalidades

### ISSUE THREAD

**Issue by brunna-martins** [Requisitos-de-Software/2023.1-Twitch#108]
## Descrição: 
O monitor disse em seu feedback que apresentássemos os requisitos que fazem parte da categoria "Funcionalidade", ao menos alguns deles, de acordo com o modelo FURPS+.

## Critérios de aceitação: 
Atualização do documento conforme o que foi pedido e conforme os padrões estabelecidos pela equipe.

## Tarefas:
Checklist de tarefas a serem feitas.
- [ ] Adição de requisitos de Funcionalidade

**Comment by RafaelN0bre** [comment]
Resolvido - [commit](https://github.com/Requisitos-de-Software/2023.1-Twitch/commit/3604081bf84378b8160980b61f7561ae1b173c73)
