### ISSUE TITLE
Melhorias PC3 - Especificação Suplementar e Hiperlinks

### ISSUE THREAD

**Issue by brunna-martins** [Requisitos-de-Software/2023.1-Twitch#109]
## Descrição: 
O monitor disse em seu feedback que apesar de apresentar o requisito relacionado à funcionalidade, faltaram hiperlinks e ligações ao documento que diz de onde veio o requisito relacionado. É necessário deixar claro o documento relacionado e adicionar hiperlinks.

## Critérios de aceitação: 
Atualização do documento conforme o que foi pedido e conforme os padrões estabelecidos pela equipe.

## Tarefas:
Checklist de tarefas a serem feitas.
- [ ] Hiperlinks nos requisitos que especificam as funcionalidades
- [ ] Relacionar ao documento de onde foram tiradas as especificações

**Comment by RafaelN0bre** [comment]
Resolvido no [commit](https://github.com/Requisitos-de-Software/2023.1-Twitch/commit/d2ae5ca63fcadd8f1c2d92a62e873c67031dbed1)
 
Adicionei os hyperlinks em todos os requisitos, e alguns exemplos nos de Funcionalidades
