### ISSUE TITLE
Adicionar referências/fontes no documento de metodologias

### ISSUE THREAD

**Issue by brunna-martins** [Requisitos-de-Software/2023.1-Twitch#28]
## Descrição: 
No documento de metodologias, ficaram faltando as referências/fontes das informações contidas no artefato.

## Critérios de aceitação: 
Fontes das informações contidas no documento.

## Tarefas:
Checklist de tarefas a serem feitas.
- [x] Adicionar referências/fontes

**Comment by diogjunior100** [comment]
Adicionado Referências e Fontes
