### ISSUE TITLE
RichPicture - Twitch

### ISSUE THREAD

**Issue by diogjunior100** [Requisitos-de-Software/2023.1-Twitch#4]
## Descrição: 
Realizar RichPicture do site Twitch

## Critérios de aceitação: 
RichPicture pronta desenhada a mão ou desenha por algum software de diagramação (LucidChart, Draw.io etc)

## Tarefas:
Checklist de tarefas a serem feitas.
- [x] Criar RichPicture
- [x] Colocar RichPicture na GitPage

**Comment by RafaelN0bre** [comment]
O Diagrama pode ser acompanhado no [LINK](https://drive.google.com/file/d/1mnqC5Ubuup-hAh9NnKpkRHpu3lBpRPtr/view?usp=sharing)
