### ISSUE TITLE
Definição dos perfis

### ISSUE THREAD

**Issue by RafaelN0bre** [Requisitos-de-Software/2023.1-Twitch#46]
## Descrição

Criação e definição dos perfis de usuário da plataforma Twitch. Deverá ser criado um formulário para captação de dados, a fim de determinar o perfil de usuário por meio da análise de dados, e inserir os resultados dentro do gh-pages

A fim de incrementar o processo de análise, caso haja tempo, produzir um dashboard iterativo utilizando alguma ferramenta de BI

## Critérios de aceitação
- [ ] Criação e definição das perguntas
- [ ] Criação do formulário
- [ ] Disseminação do formulário
- [ ] Captação de dados e inserção dentro do GH-Pages

**Comment by brunna-martins** [comment]
O formulário pode ser acessado [aqui](https://forms.office.com/r/zZz8BP0VqM).
