### ISSUE TITLE
Entrevista para elicitação de requisitos

### ISSUE THREAD

**Issue by RafaelN0bre** [Requisitos-de-Software/2023.1-Twitch#48]
## Descrição

Realizar uma entrevista como técnica de elicitação de requisitos. Deve realizar a gravação do vídeo ou áudio da entrevista, com perguntas previamente pensadas e definidas.

- [ ] Definição do entrevistado
- [ ] Confecção de perguntas
- [ ] Realização da entrevista
- [ ] Elicitação dos requisitos encontrados por meio da entrevista
- [ ] Inserção no gh-pages
    - Introdução/Metodologia
    - Gravação
    - Requisitos funcionais e não funcionais encontrados
    - Histórico de Versões

**Comment by MattSilverio** [comment]
Um dos candidatos a entrevista não deu retorno e outro disse que não consegue essa semana(23/04-29/04) , porém esse respondeu o formulário.

**Comment by MattSilverio** [comment]
Devido a falta de entrevistados, essa issue estará sendo fechada
