### ISSUE TITLE
Atas das reuniões

### ISSUE THREAD

**Issue by brunna-martins** [Requisitos-de-Software/2023.1-Twitch#9]
## Descrição: 
Até o presente momento (14/04/2023), realizamos 2 reuniões oficiais. É necessário colocar documentos curtos a respeito do que foi discutido e acordado em cada uma dessas reuniões.

## Critérios de aceitação: 
Criação de pasta para organizar os documentos relacionados a reuniões, bem como as atas de cada reunião já feita.

## Tarefas:
Checklist de tarefas a serem feitas.
- [x] Pasta para organizar as atas de reunião
- [x] Ata da primeira reunião (divisão inicial de tarefas)
- [x] Ata da segunda reunião (escolha do app)
- [x] Colocar atas de reunião no githubpages

**Comment by MattSilverio** [comment]
Reabrindo para fazer a indexação das atas.

@milenaaires , o deploy automático está configurado. Ao fazer a nova PR, pode fechar essa issue com as atas indexadas no mkdocs.yml

**Comment by milenaaires** [comment]
Atas indexadas e revisadas.
